### ISSUE TITLE
AttributeError: 'pyscipopt.scip.Model' object has no attribute 'getState'

### ISSUE THREAD

**Issue by lzr123** [WXY1427/Learn-LNS-policy#1]
Hi, when I run the train_LNS.py file in LNS_CATS directory, I get the following error:
AttributeError: 'pyscipopt.scip.Model' object has no attribute 'getState

I have followed the installation instructions given in learn2branch repository (installation instruction directed to this repo)
I installed SCIP 6.0.1 and PySCIPOPT 2.1.5

I can't find where this attribute comes from as it is not available when I look at the list of pyscipopt.scip.Model attributes.

**Comment by WXY1427** [comment]
You may need pip install --force-reinstall git+https://github.com/ds4dm/PySCIPOpt.git@ml-branching as commented in learn2branch repository.

The modifided pyscipopt version is in  https://github.com/ds4dm/PySCIPOpt/blob/ml-branching/src/pyscipopt/scip.pyx#L4203, where the getState function exists.
